---
- hosts: all
  become: yes
  become_user: root
  tasks: 
  - name: update apt packages
    apt:
     upgrade: yes
     update_cache: yes
     
  - name: Install Qemu Guest Tools
    ansible.builtin.apt:
      pkg:
      - qemu-guest-agent

  - name: Install Kubernetes Server Dependecies
    ansible.builtin.apt:
      pkg: 
      - apache2
      - apt-transport-https
      - ca-certificates
      - curl 
      - gpg
      - containerd
      - socat
      - python3
      - python3-kubernetes

  - name: Install GPG Key
    shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    
  - name: Setup Keyring
    shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
    
  - name: update apt packages
    apt:
     upgrade: yes
     update_cache: yes
    
  - name: Install Kubernetes Server Dependecies
    ansible.builtin.apt:
      pkg: 
      - kubelet 
      - kubeadm 
      - kubectl

  - name: Install Kubectl
    shell: systemctl enable --now kubelet

  - name: Disable swap for current session
    command: swapoff -a

  - name: Disable swap permanently, persist reboots
    replace:
      path: /etc/fstab
      regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
      replace: '#\1\2\3swap\4'
      backup: yes

  - name: Configure Sysctl IP Foward
    ansible.posix.sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: true
      state: present
      reload: true

  - name: Rebooting Machine post config changes
    ansible.builtin.reboot:


- hosts: Kubernetes_Master
  tasks: 
  - name: initialize the cluster
    #hosts: Kubernetes Master
    become: yes
    become_user: root
    shell: kubeadm init --pod-network-cidr=192.168.0.0/16 
      #ignore_errors: yes
    
  - name: create .kube directory
    #hosts: Kubernetes Master
    file:
      path: /home/timmy/.kube
      state: directory
      mode: 0755

  - name: copies admin.conf to users kube config
    #hosts: Kubernetes Master
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/timmy/.kube/config
      remote_src: yes
      owner: timmy
      group: timmy

  - name: Download tigera operator file
    shell: wget https://raw.githubusercontent.com/projectcalico/calico/v3.28.2/manifests/tigera-operator.yaml
    
  - name: apply manifest tigera-operator manifest
    kubernetes.core.k8s:
      src: "~/tigera-operator.yaml"
      state: present

  - name: Download calico custom resources
    shell: wget https://raw.githubusercontent.com/projectcalico/calico/v3.28.2/manifests/custom-resources.yaml
    
  - name: apply manifest tigera-operator resources
    kubernetes.core.k8s:
      src: "~/custom-resources.yaml"
      state: present
...
