---
- hosts: all
  become: yes
  become_user: root
  tasks: 
  - name: update apt packages
    apt:
     upgrade: yes
     update_cache: yes

  - name: Install Kubernetes Server Dependecies
    ansible.builtin.apt:
      pkg: 
      - apache2
      - apt-transport-https
      - ca-certificates
      - curl 
      - gpg

  - name: Install GPG Key
    ansible.buitin.shell: 
    cmd: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    
  - name: Setup Keyring
    ansible.builtin.shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
    
  - name: update apt packages
    apt:
     upgrade: yes
     update_cache: yes
    
  - name: Install Kubernetes Server Dependecies
    ansible.builtin.apt:
      pkg: 
      - kubelet 
      - kubeadm 
      - kubectl

  - name: Install Kubectl
    ansible.builtin.shell: systemctl enable --now kubelet
    
...
