---
- hosts: all
  become: yes
  become_user: root
  tasks: 
  - name: update apt packages
    apt:
     upgrade: yes
     update_cache: yes
     
  - name: reboot servers post patch
    ansible.builtin.reboot:
    reboot_timeout: 3600
...
