---
- hosts: Kubernetes_Master
  tasks: 
  - name: apply manifest tigera-operator manifest
    kubernetes.core.k8s:
      src: "https://raw.githubusercontent.com/projectcalico/calico/v3.28.2/manifests/tigera-operator.yaml"
      state: present
      
    - name: apply manifest tigera-operator resources
      kubernetes.core.k8s:
        src: "https://raw.githubusercontent.com/projectcalico/calico/v3.28.2/manifests/custom-resources.yaml"
        state: present
...
