---
- hosts: Kubernetes_Master
  become: yes
  become_user: root
  tasks: 
  
  - name: install tigera operator
    #hosts: Kubernetes Master
    become: yes
    become_user: timmy
    command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.2/manifests/tigera-operator.yaml
    #args:
      #chdir: /home/timmy/
      
  - name: install calico resources
    #hosts: Kubernetes Master
    become: yes
    become_user: timmy
    command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.2/manifests/custom-resources.yaml
...
