---
- hosts: all
  become: yes
  become_user: root
  tasks: 
  
  - name: Add Example GPG key
    ansible.builtin.get_url:
      url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
      dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
...
