---
- hosts: Kubernetes_Master
  tasks: 
  - name: Getting join command from the master node
    become: yes
    become_user: root
    shell: kubeadm token create --print-join-command
    register: join_command
 
  - name: Setting join command…
    set_fact:
      join_command: "{{ join_command.stdout_lines[0] }}"

  - name: add variables to dummy host
    add_host:
      name: "variable_holder"
      shared_variable:  "{{ join_command }}"

- hosts: Kubernetes_Worker
  tasks:
  - name: Joining to the cluster
    become: yes
    become_user: root
    shell: "{{ hostvars['variable_holder']['join_command'] }}"
...
