---
- hosts: Kubernetes_Master
  tasks: 
  - name: Getting join command from the master node
    become: yes
    become_user: root
    shell: kubeadm token create --print-join-command
    register: join_command
 
  - name: Setting join command…
    set_fact:
      join_command: "{{ join_command.stdout_lines[0] }}"

- hosts: Kubernetes_Worker
  tasks:
  - name: Joining to the cluster
    become: yes
    become_user: root
    shell: "{{ hostvars['192.168.3.171']['join_command'] }}"
...
