---
- hosts: all
  become: yes
  become_user: root
  tasks: 
  
  - name: Add an Apt signing key, will not download if present
    ansible.builtin.apt_key:
      url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
      state: present
...
