---
- hosts: all
  become: yes
  become_user: root
  tasks: 
  
  - name: Add Example GPG key
    ansible.builtin.get_url:
      url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
      dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      mode: '0644'
      force: true

  - name: Add Example repo
    ansible.builtin.apt_repository:
      filename: example-repo
      repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
...
